catullus_63 = [

##1-5
    [
        "celer",
        "ratis",
        "nemus",
        "tetigi",
        "opacus",
        "citatus",
        "redimio",
        "stimulo",
        "furo",
        "rabies",
        "vagus",
        "devello",
        "ile",
        "acuo",
        "pondus",
    ],

##6-14
    [
        "silex",
        "initia",
        "quatio",
        "tergum",
        "tener",
        "adorior",
        "tremebundus",
        "comes",
        "cavus",
        "simul",
        "Dindymenae",
        "velut",
        "exul",
        "seco",
        "membrum",
        "maculo",
        "recens",
        "typanum",
        "desino",
    ],

##15-21
    [
        "exsequor",
        "salum",
        "rapidus",
        "truculentus",
        "pelagus",
        "eviro",
        "evirastis",
        "nimius",
        "odium",
        "hilaro",
        "era",
        "mora",
        "tardus",
        "sequimini",
        "reboo",
    ],

##22-26
    [
        "tibicen",
        "Phryx",
        "secta",
        "error",
        "curvus",
        "calamus",
        "hederiger",
        "sacra sancta",
        "sancio",
        "ululatus",
        "suevi",
        "suesco",
        "cohors",
        "volito",
        "tripudium",
    ],

##26-31
    [
        "cedo",
        "decet",
        "thiasus",
        "repens",
        "repente",
        "trepido",
        "remugio",
        "recrepo",
        "viridis",
        "citus",
        "Ida",
        "propero",
        "cecini",
        "nothus",
        "furibundus",
        "cupidus",
    ],

##31-37
    [
        "anhelo",
        "vado",
        "comito",
        "veluti",
        "juvenca",
        "vito",
        "onus",
        "indomitus",
        "properipes",
        "lassulus",
        "Ceres",
        "piger",
        "labo",
        "languor",
        "operio",
    ],
    
##    [
##        "",
##        "",
##        "",
##        "",
##        "",
##        "",
##        "",
##        "",
##        "",
##        "",
##        "",
##        "",
##        "",
##        "",
##        "",
##    ],
]
