classical_arabic_vocab = [
    [
        "go out, leave",
        "create",
        "enter",
        "was",
        "God",
        "earth",
        "garden; paradise",
        "man, male human being",
        "messenger, apostle",
        "city, town",
        "believer",
        "prophet",
        "particle that introduces a nominal clause",
        "where?",
        "from, among, of",
        "in",
        "and",
        "Ahmad",
        "Muhammad",
        "Moses",
    ],

    [
        "woman; wife",
        "girl; daughter",
        "garden",
        "eye; spring",
        "night(time)",
        "(one) night",
        "tonight",
        "boy, child",
        "hand, arm",
        "small, little; young",
        "close, near, nearby",
        "big, large; old; great",
        "here",
        "to, for",
    ],

    [
        "go",
        "find",
        "son",
        "name",
        "house, dwelling",
        "lord, master",
        "old man, elder, chief",
        "book",
        "king",
        "Mecca",
        "day",
        "today",
        "handsome, beautiful",
        "great, huge, magnificent",
        "to (motion or direction toward)",
    ],

    [
        "sign, token; verse of the Koran",
        "that",
        "good, a good thing",
        "sky, heaven",
        "slave, servant (of God)",
        "sincere, devoted",
    ],

    [
        "prostrate, fall/bow down",
        "come/go down, descend, stop; bring",
        "finger",
        "human being, person, man",
        "The Merciful",
        "mud, clay",
        "enemy",
        "heart",
        "angel",
        "between, among",
        "on, onto; against, over"
        "interrogative particle",
        "except for",
        "Adam",
        "Satan",
    ],
    
    [
        "go out against, appear to",
        "go into (the presence of)",
        "hear",
        "say",
        "hinder access; prevent; forbid",
        "last, final; end",
        "better",
        "religion",
        "day of judgement, doomsday",
        "pious",
        "rich",
        "poor",
        "voice, words, speech",
        "unbeliever, infidel",
        "infidelity, unbelief",
        "when (conjunction + perf. verb)",
        "and then, and so",
        "particle that emphasizes the perfective aspect of a perfect verb",
        "Gabriel",
        "Lot",
        "Noah",
    ],
    
    [
        "order, command",
        "make, put",
        "write; prescribe",
        "be ungrateful; disbelieve, perform an act of infidelity",
        "curse",
        "ear",
        "nose",
        "spirit",
        "mate, spouse",
        "tooth; age",
        "thing",
        "all, every, whole",
        "fire",
        "-self (reflexive pronoun)",
        "soul",
        "one (adj.)",
        "when (conjunction + perf. verb)",
        "with",
        "away from, out of (highly idiomatic range of meanings)",
    ],

    [
        "come, come to; bring (1)",
        "rise up, arise; go; undertake",
        "not to be",
        "die",
        "the next world, the life to come",
        "those",
        "that (fem. sg.)",
        "life",
        "this world, this life",
        "the life of this world",
        "that (masc. sg.)",
        "prayer, ritual prayer",
        "little (bit); slight, few",
        "many, much",
        "goods, wares, chattel",
        "place, location, position",
        "this (masc. sg.)",
        "this (fem. sg.)",
        "these",
    ],

    [
        "come; bring (2)",
        "call, call upon, call out to, summon",
        "pelt; cast",
        "see, consider",
        "pardon",
        "people, nation, tribe",
        "fem. sg. relative pronoun",
        "masc. sg. relative pronoun",
        "masc. pl. relative pronoun",
        "like (proclitic)",
        "thus, likewise",
        "what?",
        "but, rather",
        "O",
        "Jesus",
        "Mary",
    ],

    [
        "send, send forth; resurrect",
        "mention, make mention of; recollect",
        "go astray, get lost",
        "do",
        "lead, lead aright",
        "human being, mankind",
        "water",
        "after",
        "with, in the possession/opinion/presence/house of",
        "before",
        "afterwards",
        "from among, from the presence/possession of",
        "beforehand",
        "'really', emphasizing particle",
        "not",
        "the Gospel",
        "the Torah, the Pentateuch",
    ],

    [
        "take, size; take hold",
        "ask",
        "worship",
        "two",
        "Monday",
        "other",
        "one (pronoun)",
        "Sunday",
        "dust, earth, ground",
        "mountain",
        "new",
        "creation, created beings, people",
        "mercy",
        "merciful, compassionate",
        "Sabbath",
        "Saturday",
        "Jews",
        "Jew, Jewish",
        "that which, what",
        "everything that, all that which",
        "who? (interrogative); he who, whoever",
        "everyone who, all who",
    ],

    [
        "eat, consume",
        "bear witness, testify",
        "tell the truth, be truthful",
        "know, learn; realize",
        "delude, deceive",
        "lie, tell a lie",
        "look, regard",
        "people; family",
        "the people of a city",
        "the People of the Book",
        "sun",
        "knowledge, learning",
        "fruit",
        "noble, generous, honorable",
        "news",
        "certainty",
        "certain knowledge",
        "that (subordinating conjunction, follows verbs of perception)",
        "proclitic particle for the future explicit",
        "particle for the future explicit",
        "why?",
        "what?",
        "Sheba",
        "Solomon",
    ],

    [
        "give",
        "father, progenitor",
        "(dual) parents",
        "'my dear father'",
        "brother",
        "sister",
        "god, deity",
        "those in authority",
        "man, male",
        "possessor of, owner of",
        "idol",
        "not (invariable negative particle)",
        "except, except for",
        "that...not, that...no",
        "or",
        "on the contrary, but rather",
        "interrogative particle",
        "Aaron",
        "Pharaoh",
        "Egypt",
    ],

    [
        "flee",
        "pass",
        "go astray, get lost",
        "devout, God-fearing",
        "forceful, violent",
        "evil, bad(ness)",
        "number",
        "strength, force, might",
        "strong, powerful",
        "property, possession, wealth",
        "people",
    ],

    [
        "fear, be afraid",
        "travel, set out, depart",
        "wrong, treat unjustly, oppress",
        "do, perform",
        "sleep",
        "good works, good deeds",
        "injustice, tyranny",
        "world",
        "universe",
        "torment",
        "deed, job, chore, work",
        "likeness, similarity",
        "like (preposition)",
        "on the day when",
    ],

    [
        "build",
        "know, comprehend something; be aware",
        "find something acceptable; be pleased/content",
        "will, want",
        "injure, harm",
        "disobey",
        "meet, encounter",
        "forget",
        "faith, believing",
        "alms, almsgiving",
        "light",
        "when (+ perf. verb)",
        "if",
        "which? what kind of?",
        "Israel",
        "Ishmael",
    ],

    [
        "make...again; send/bring/take back; reply",
        "be patient, have patience",
        "find",
        "wish",
        "inherit from, be the heir of",
        "contain, hold, have the capacity for",
        "promise someone; threaten someone",
        "give, bestow",
        "some of",
        "each other",
        "indisputable evidence, proof",
        "father, progenitor",
        "parents",
        "or? (continues alternatives in interrogative clause)"
        "below; to the exclusion of, disregarding, up to but not including",
    ],

    [
        "draw near to, approach",
        "forbid someone",
        "permission",
        "tree",
        "demon, devil",
        "so that, in order that",
        "until",
        "before",
        "it was not possible",
        "that...not",
        "that",
        "in order that, until",
        "in order that",
        "'will not' (negative future)",
    ],

    [
        "lead, guide, show",
        "be merciful to, have mercy on",
        "inhabit, dwell in",
        "forgive",
        "advise, give good advice to; take good care of",
        "time",
        "at the time when",
        "at the time of",
        "village",
        "clear, obvious",
        "leaf (of a tree), folio, sheet (of paper)",
        "where, wherever (...)",
        "negative past definite particle",
        "Zuleikha",
        "Joseph",
    ],

    [
        "seem, appear",
        "lose, suffer loss, forfeit; go astray, perish",
        "last forever, be immortal",
        "taste",
        "narrate, tell",
        "go down, descend, collapse",
        "community",
        "talk, conversation; report, account",
        "narrative relating an utterance of Muhammad",
        "narrative in which God speaks in the first person",
        "eternity, immortality",
        "enmity, hostility",
        "resurrection",
        "prophetic, relating to a prophet",
        "only, specifically",
        "(after negative clause) however, rather",
        "as though",
        "how?",
        "above, over",
        "Jacob",
    ],


    [
        "cry, weep",
        "pass judgement",
        "laugh",
        "visit the sick",
        "return",
        "fall ill, be sick",
        "first",
        "free",
        "so-and-so",
        "sick, ill",
        "if (possible conditional), when",
        "if (contrary to fact",
        "were it not for",
        "as, just as",
    ],


    [
        "begin, start",
        "hide, conceal",
        "live",
        "know, recognize",
        "kill",
        "reach, arrive at; appear, show up",
        "gate, door",
        "far, distant",
        "way, path",
        "in God's cause",
        "treasure",
        "likeness, parable, simile",
        "'X is like Y'",
        "rain",
        "dead",
        "according to how",
    ],


    [
        "VII depart, go on, proceed on one's way, move freely",
        "split, cleave",
        "VII be split apart, cloven asunder",
        "neglect, be unmindful",
        "cut",
        "VII get cut off",
        "turn around, turn upside down",
        "VII return, turn back, be changed",
        "put down, lay aside",
        "a sin (for someone) (to do something)",
        "precaution",
        "take one's precaution",
        "arms, weapon",
        "group, band, party",
        "heel",
        "place",
        "perhaps",
        "behind, beyond, the other (far) side of",
        "he turned back on his heels, retraced his steps, went back whence he came",
    ],


    [
        "VIII adopt",
        "follow",
        "VIII follow, heed, pursue",
        "leave, abandon",
        "VIII draw near",
        "walk, go on foot",
        "fill",
        "VIII be filled, full",
        "be of benefit to, avail",
        "VIII make use, avail oneself",
        "total, whole, entirety",
        "peace, well-being",
        "calf",
        "crowd, assembly, council of notables",
        "day (as contrasted to night)",
        "then, therefore",
        "perhaps",
        "Gehenna, Hell",
    ],


    [
        "VII be proper, seemly, be necessary",
        "VIII strive for, aspire to, desire",
        "be ignorant, not know, be foolish",
        "VIII choose, select",
        "VIII be rightly guided, be shown the right way",
        "ward off, protect, guard someone/thing from someone/thing",
        "VIII beware, be on one's guard, fear (God",
        "companion, friend; master",
        "star",
        "lust, passion",
        "after",
        "other than, non-, un-",
        "the Kinana tribe, part of one of the two great divisions of the northern Arabs",
        "the Quraysh",
        "Hashim",
    ],


    [
        "flow (water), blow (wind); happen, come to pass",
        "strike, hit, smite",
        "VIII clash, be upset",
        "plot for the downfall of, conspire",
        "stone, rock",
        "vision",
        "bird",
        "rod, staff",
        "end, final outcome",
        "moon",
        "heavenly body, star",
        "river, stream",
        "beneath, below",
        "lo and behold",
        "he gave as an example",
    ],


    [
        "permit (someone) (to do something)",
        "II give the call to prayer",
        "II subjugate",
        "recite, read aloud",
        "touch",
        "possess, rule, reign",
        "II put in possession of, make king",
        "be Jewish, practice Judaism",
        "II Judaize",
        "good, beautiful",
        "good deed",
        "praise",
        "praise (be to) God",
        "the Koran",
        "partner",
        "friend, helper, supporter",
        "Magian, adherent of Mazdaism",
        "Christian, follower of the Nazarene",        
    ],


    [
        "spread, stretch out (transitive)",
        "return",
        "fornicate, commit adultery",
        "II name, stipulate",
        "II pray, perform the ritual prayer",
        "rise (sun, moon, etc.)",
        "VIII be informed, observe something closely",
        "II make someone/thing face/turn (towards)",
        "VIII turn towards, set out",
        "turn aside/away (from); put someone in charge of",
        "term, appointed time, instant of death",
        "Islam",
        "right, truth",
        "head",
        "north",
        "left (hand)",
        "strange, foreign",
        "face",
        "oath",
        "right (hand)",
        "wherever (+ perf. or juss. as conditional type)",
        "there, in that place",
        "then, next, afterwards",
        "blessed be",
    ],


    [
        "read, recite (out loud)",
        "be level, equal, equivalent",
        "II equalize, put on the same level (with); make/shape properly",
        "VIII be even, on a par; stand upright; sit down (on); be done (food), be mature, be ripe (fruit)",
        "V accept, receive (something)",
        "be capable (of)",
        "II appoint, determine, foreordain",
        "II sacrifice; allow near (to), let approach",
        "V approach, get near (to)",
        "speak to, address",
        "V speak (with)",
        "II prepare, make ready",
        "V be prepared, in readiness, get ready",
        "turn, face (toward)",
        "direction of prayer/toward Mecca",
        "sacrifice",
        "word",
        "master, patron",
        "form, shape",
    ],


    [
        "announce (something) as good news (to)",
        "be forbidden",
        "II make unlawful, proscribe (for)",
        "know thoroughly, be fully acquainted (with)",
        "provide with sustenance, means of subsistence",
        "decide, foreordain",
        "VII be completed, concluded",
        "V wish for, desire; make a wish for",
        "II give (someone) full due; give a full share of",
        "V take/get one's full share of, receive fully",
        "V (passive) die, pass on (euphemistic)",
        "mother",
        "good news",
        "news, piece of information",
        "evil, ill",
        "how?",
        "whever (+ conditional type)",
        "yes",
        "Isaac",
        "Zacharias",
        "Messiah",
    ],


    [
        "be completed, finished, fulfilled",
        "reckon, consider (someone) (as)",
        "figure, make an account",
        "come after, take the place of, lag (behind)",
        "II appoint as successor",
        "VIII differ (from), dispute (over), frequent (a place)",
        "pass away, come to an end; (neg.) continue, abide",
        "keep on, be still (doing something) (occurs int he negative + imperf. ind. or act. part.)",
        "bew quick, fast",
        "break",
        "II smash, break to pieces",
        "VII get broken",
        "almost, scarcely (verb)",
        "be pure, clean",
        "II purify",
        "V cleanse oneself, perform ablutions",
        "blame, reproach (for)",
        "sake",
        "for the sake of",
        "genie, the djinn, invisible beings who interfere in men's lives",
        "evil",
        "evil deed",
    ],


    [
        "be/feel safe, trust",
        "IV believe (in)",
        "IV love, like, want",
        "IV turn one's back (on), go back, flee, run away",
        "be safe and sound, intact",
        "II keep from harm, hand over intact",
        "IV submit, surrender",
        "be reasonable, be endowed with reason",
        "II make reasonable, bring to reason",
        "IV come/go forward, advance (on/to)",
        "the back/rear side of something",
        "power, authority",
        "reason, rationality; intellect, mind",
        "the fore/front side of something",
        "by (used in oaths)",
        "'he turned and ran away'",
    ],


    [
        "II substitute (something) (for something else)",
        "V change, exchange (something) (for something else)",
        "reach, attain, amount to",
        "IV make someone/thing reach; announce, inform",
        "live, be alive",
        "IV bring to life, revivify",
        "be mistaken, make a mistake, sin",
        "IV err, miss, be off target",
        "IV want",
        "IV hit the mark, afflict",
        "IV (passive) be stricken, afflicted",
        "IV obey",
        "IV inspire (someone) (with something)/(that)",
        "alive",
        "darkness",
        "ever; (+ negative) never",
        "(+ subjunctive) on condition that",
        "'he reached maturity'",
    ],


    [
        "give water to, give to drink",
        "IV give water to, give to drink",
        "X ask for water",
        "V give alms",
        "X have the endurance/capability for, be able/capable of",
        "IV feed",
        "X ask for food",
        "hurry, hasten (intransitive)",
        "II hasten (transitive)",
        "V hurry, hasten (intransitive); be ahead of, precede",
        "X be in a hurry, rush",
        "II enable someone to enjoy (something); equip",
        "V enjoy (something)",
        "X enjoy, relish (something)",
        "help, assist (against)",
        "VIII be victorious, triumph (over), take revenge (on)",
        "X ask for assistance",
        "iron",
        "wind",
        "food, victuals",
        "orphan",
        "when?",
        "after (conj.)",
    ],


    [
        "III take to task (for)",
        "III entice",
        "III make peace",
        "VI be reconciled",
        "III witness",
        "III trade, do business with",
        "VI trade, do business with each other",
        "III confront, stand opposite",
        "VI be face to face, get together",
        "III fight with",
        "III oppose, resist",
        "VI resist each other",
        "III write to",
        "VI correspond with each other",
        "III outnunber",
        "VI band together",
        "III speak with",
        "VI blame each other",
        "III resemble",
        "VI resemble each other, be alike",
        "VI pretend to be sick",
        "III put up resistance to",
        "VI pretend to forget",
        "III argue, debate",
        "VI dispute with one another",
        "VI love one another",
    ],


    [
        "be friendly, on intimate terms (with); perceive",
        "II put at ease, tame",
        "III be friendly, cordial to",
        "IV keep company, observe, espy",
        "X be sociable, on familiar terms with",
        "seek shelter, refuge",
        "IV take refuge (at), give shelter to",
        "III bless (someone/thing)",
        "VI be blessed",
        "III endeavor, strive",
        "VIII work hard, be industrious",
        "be hungry",
        "be high, tall, rise (above)",
        "VI be exalted (over), be sublime",
        "VI (imperative) 'come on!'",
        "X rise, tower (over), be master (of)",
        "III call/cry out to, proclaim",
        "III be hypocritical, dissimulate",
        "IV spend, expend",
        "part company with, be separated from",
        "III migrate",
        "VI desert each other, break up",
        "humanity (as opposed to beasts, djinn, etc.)",
        "blessing",
        "sin",
        "grave",
        "(+ construct) 'glory be to'",
    ],


    [
        "look, see, understand",
        "II make see, enlighten",
        "IV see, behold",
        "V reflect (on)",
        "X be able to see",
        "IV become (in the morning); get/wake up in the morning",
        "IV give/issue a (legal) opinion/counsel",
        "X seek opinion/counsel from someone (concerning...)",
        "separate, part (int.), distinguish (between/among)",
        "II part, separate (trans.)",
        "III disengage oneself from, part with, quit",
        "V be separated, divided, scattered",
        "VIII be separated, divided, scattered",
        "mute, dumb",
        "white",
        "red",
        "green",
        "blue",
        "black",
        "yellow",
        "deaf",
        "blind",
        "vision, sight, insight",
        "beast, (riding) animal)",
        "(legal) opinion, counsel",
        "morning, dawn, daybreak",
        "as for",
        "yes (affirmative response to a negative question",
        "even if",
    ],


    [
        "requite, reward, punish (for)",
        "III requite, reward, punish (for)",
        "preserve, protect, memorize",
        "III watch out (for), be mindful (of)",
        "VIII (+ prep.) guard, maintain",
        "X commit (something) (to the charge of)",
        "IV surround (someone) (with)",
        "VIII be careful, on one's guard",
        "steal, rob",
        "VII be/get stolen",
        "VIII filch, pilfer",
        "rot, decay, be wicked, vain",
        "IV spoil, corrupt, act wickedly",
        "not to know/recognize, deny, disown",
        "IV refuse to acknowledge, disavow, disclaim",
        "entrust (to)",
        "II authorize, put in charge (of)",
        "V rely (on), depend (upon), put one's confidence (in)",
        "VIII rely (on), depend (upon), put one's confidence (in)",
        "wares, merchandise",
        "flame, shooting star",
        "small weight",
        "act of favor/kindness, good deed",
        "refuge, recourse, retreat",
        "abomination, objectionable act",
        "'he eavesdropped'",
    ],


    [
        "send/bring/take back, ward off, return; reply (to)",
        "V be reflected, recur; waver, be uncertain, hesitate",
        "VIII go back, revert, apostasize (from)",
        "X reclaim, get back",
        "be sad, grieved",
        "IV be tranquil, at peace, assured",
        "seek protection (with) (from)",
        "II place someone under the protection (of) (against)",
        "X seek protection (with) (from)",
        "be absent, vanish",
        "be cool",
        "be glad, delighted (in)",
        "perish, die",
        "IV destroy, cause to perish",
        "X exhaust oneself",
        "leave; (+ jussive) let, allow",
        "despair, give up hope (of)",
        "IV deprive of hope",
        "X despair, give up hope (of)",
        "sorrow, grief",
        "alms, charity",
        "that which is invisible, the transcendental/supernatural (realm)",
        "joy, delight",
        "neither...nor",
    ],


    [
        "turn away (from), renounce, relent, repent (towards)",
        "IV (+ prep.) make a sign, indicate",
        "fast (verb)",
        "count, number (verb)",
        "subdue, vanquish",
        "marry",
        "be humble",
        "thousand",
        "year",
        "month",
        "year",
        "number (noun)",
        "hundred",
        "consecutive",
        "time, instance",
        "poor, unfortunate",
    ],


    [
        "make the pilgrimage to Mecca",
        "push away, repel",
        "be more (than), increase (int.)",
        "II increase (trans.)",
        "VIII grow, multiply",
        "be good, pleasant",
        "II charge (with), recommend; bequeath (something) (to)",
        "IV charge (with), recommend; bequeath (something) (to)",
        "befall, occur, fall down",
        "female",
        "part, section",
        "male",
        "good, pleasant, agreeable",
        "perfume, pleasant aroma",
        "half",
        "bequest, legacy; directive, commandment",
    ],
]
