ur_III_signs = [   
    [
        "DN determinative (ᵈX)",
        "GN determinative (Xᵏⁱ)",
        "Nanna —",
        "Nammu —",
        "Ur-ᵈNammu —",
        "Urim₅ (Uri₅) —",
        "nin —",
        "an —",
        "ur —",
        "lugal —",
        "e₂ —",
        "du₃ —",
        "na",
        "a",
        "ni",
        "ma",
        "ke₄",
        "mu",
    ],

    [
        "Inanna —",
        "'Sumer' (GN)",
        "'Akkad' (GN)",
        "nitaḫ (nita) —",
        "kalag (kala) —",
        "ga",
    ],
    [
        "bad₃ —",
    ],
    [
        "Ningal —",
        "til₃ (ti) —",
        "a...ru —",
        "nam",
        "la",
        "še₃",
    ],
    [
        "Enlil —",
        "lil₂",
        "Enerinnun",
        "nun",
        "erin₂",
        "kur —",
        "id₂ (i₇) —",
        "nidba —",
        "ba-al —",
        "ra",
        "ka",
    ],
    [
        "wooden object determinative g̃iš (ᵍⁱˢX)",
        "An (DN, masc",
        "dig̃ir —",
        "ᵍⁱˢkiri₆ —",
        "barag (bara₂) —",
        "ki —",
        "maḫ —",
        "sikil —",
        "gub —",
        "re",
        "ne",
    ],
    [
        "lu₂",
        "la₂",
        "in",
    ],
    [
        "E₂-kur —",
        "ki... ag̃a₂ —",
        "g̃a₂",
    ],
    [
        "'Uruk' —",
        "E₂-temen-ni₂-guru₃ Etemenniguru —",
        "dumu —",
        "sag̃ —",
        "en —",
        "gi₄ —",
        "bi, be₂",
    ],
    [
        "Šul-gi —",
        "an-ub —",
        "da —",
        "limmu₂ —",
        "ba",
    ],
]
