writing_prompts = [
    "A person arrives at a place they’ve never been before.",
    "Two people have a conversation while waiting for something.",
    "Someone discovers an object they weren’t expecting to find.",
    "A character completes a routine task that doesn’t go exactly as planned.",
    "Write about a journey from one location to another.",
    "A delivery arrives at an unusual time.",
    "Someone reads a message that changes their schedule.",
    "A character enters a room and notices what’s inside.",
    "Two strangers are seated next to each other for an extended period.",
    "A character prepares for an upcoming event.",
    "Someone loses something and goes looking for it.",
    "A person reflects on a recent decision they made.",
    "Write about a normal day that includes one unexpected interruption.",
    "A character observes a public space for 10 minutes.",
    "Someone is given instructions they don’t fully understand.",
    "A person waits for news.",
    "A character fixes something that’s broken.",
    "Two people meet again after a long time apart.",
    "A character makes a small but significant choice.",
    "Someone discovers a door they’ve never noticed before.",
    "A character gets lost.",
    "A person notices that time is moving differently.",
    "Two friends have an argument.",
    "A person is torn between two decisions.",
    "A character finds an unexpected object.",
    "Someone deals with an unexpected change in their life.",
    "A character finds something they've been looking for for a long time, but doesn't know what to do now that they have it.",
]
